// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAryDgfBSD_Dfcio6K6AZWnGWF25uXi1WQ',
    appId: '1:434421419563:web:87f1a546f29256a383246e',
    messagingSenderId: '434421419563',
    projectId: 'first60days-d1785',
    authDomain: 'first60days-d1785.firebaseapp.com',
    storageBucket: 'first60days-d1785.firebasestorage.app',
    measurementId: 'G-1RHWHSDJJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYPeyVc-foL6Ui3QNRGFmkkWK9OuUxrv8',
    appId: '1:434421419563:android:08a679d12f16edbb83246e',
    messagingSenderId: '434421419563',
    projectId: 'first60days-d1785',
    storageBucket: 'first60days-d1785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf5gWAFrC_8Th4cjmB4O4jt-UTenUnGP0',
    appId: '1:434421419563:ios:10e773926cd3639b83246e',
    messagingSenderId: '434421419563',
    projectId: 'first60days-d1785',
    storageBucket: 'first60days-d1785.firebasestorage.app',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );

}