/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-login': RouteRecordInfo<'admin-login', '/admin/login', Record<never, never>, Record<never, never>>,
    'admin-statistics-view-statistics': RouteRecordInfo<'admin-statistics-view-statistics', '/admin/statistics/view-statistics', Record<never, never>, Record<never, never>>,
    'admin-threshold-edit-threshold-id': RouteRecordInfo<'admin-threshold-edit-threshold-id', '/admin/threshold/edit-threshold/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-threshold-manage-threshold': RouteRecordInfo<'admin-threshold-manage-threshold', '/admin/threshold/manageThreshold', Record<never, never>, Record<never, never>>,
    'admin-trainer-create-trainer': RouteRecordInfo<'admin-trainer-create-trainer', '/admin/trainer/create-trainer', Record<never, never>, Record<never, never>>,
    'admin-trainer-manage-trainer': RouteRecordInfo<'admin-trainer-manage-trainer', '/admin/trainer/manage-trainer', Record<never, never>, Record<never, never>>,
    'admin-user-create-user': RouteRecordInfo<'admin-user-create-user', '/admin/user/create-user', Record<never, never>, Record<never, never>>,
    'admin-user-edit-user-id': RouteRecordInfo<'admin-user-edit-user-id', '/admin/user/edit-user/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-user-manage-user': RouteRecordInfo<'admin-user-manage-user', '/admin/user/manage-user', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'trainer': RouteRecordInfo<'trainer', '/trainer', Record<never, never>, Record<never, never>>,
    'trainer-baby-assistant-id': RouteRecordInfo<'trainer-baby-assistant-id', '/trainer/baby_assistant/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'trainer-journal-entries-journal-entries': RouteRecordInfo<'trainer-journal-entries-journal-entries', '/trainer/journal_entries/journal_entries', Record<never, never>, Record<never, never>>,
    'trainer-login': RouteRecordInfo<'trainer-login', '/trainer/login', Record<never, never>, Record<never, never>>,
    'trainer-user-manage-users': RouteRecordInfo<'trainer-user-manage-users', '/trainer/user/manage-users', Record<never, never>, Record<never, never>>,
    'trainer-user-view-baby-id': RouteRecordInfo<'trainer-user-view-baby-id', '/trainer/user/view-baby/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'trainer-user-view-stats-id': RouteRecordInfo<'trainer-user-view-stats-id', '/trainer/user/view-stats/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'trainer-user-view-user-id': RouteRecordInfo<'trainer-user-view-user-id', '/trainer/user/view-user/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
