/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-login': RouteRecordInfo<'admin-login', '/admin/login', Record<never, never>, Record<never, never>>,
    'admin-user-create-user': RouteRecordInfo<'admin-user-create-user', '/admin/user/create-user', Record<never, never>, Record<never, never>>,
    'admin-user-edit-user-id': RouteRecordInfo<'admin-user-edit-user-id', '/admin/user/edit-user/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-user-manage-user': RouteRecordInfo<'admin-user-manage-user', '/admin/user/manage-user', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'trainer': RouteRecordInfo<'trainer', '/trainer', Record<never, never>, Record<never, never>>,
    'trainer-create-trainer': RouteRecordInfo<'trainer-create-trainer', '/trainer/create-trainer', Record<never, never>, Record<never, never>>,
    'trainer-login': RouteRecordInfo<'trainer-login', '/trainer/login', Record<never, never>, Record<never, never>>,
    'trainer-manage-trainer': RouteRecordInfo<'trainer-manage-trainer', '/trainer/manage-trainer', Record<never, never>, Record<never, never>>,
  }
}
